sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py install
  - pip install coveralls
script:
  - python setup.py test
  - coverage run --omit=tests/*,setup.py,*.egg --include=iiif-presentation-validator.py setup.py test
after_success:
  - coveralls
before_deploy:
  - mkdir build; zip -q -r build/presentation-validator.zip .
